version: '3'
services:
  openas2:
    build: .
    volumes:
      - ./Server/src/config:/opt/openas2/config
      - data_volume:/opt/openas2/data
    ports:
      - 4080:10080
      - 4081:10081
      - 8443:8443
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .env
volumes:
  data_volume:
