version: '3'
services:
  openas2:
    image: public.ecr.aws/j6w3y6o7/firstb2b-openas2:latest
    volumes:
      - ./Server/src/config:/opt/openas2/config
      - ./data:/opt/openas2/data
      - ./logs:/opt/openas2/logs
    ports:
      - 4080:10080
      - 4081:10081
      - 8443:8443
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .env
